@HostelTransportAPI_HostAddress = @HostelTransportAPI_HostAddress = https://college-hostel-transport-management.onrender.com

GET {{HostelTransportAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
